name: Gh-Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '16'
      - uses: subosito/flutter-action@v1
        with:
          node-version: '16'
      - uses: bluefireteam/flutter-gh-pages@v7
